/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Pro {
    id: Principal;
    bio: string;
    categorie: Categorie;
    actif: boolean;
    ville: string;
    subscriptionExpiry: bigint;
    name: string;
    createdAt: bigint;
    email: string;
    modeTravail: ModeTravail;
    subscriptionActive: boolean;
    adresse: string;
    rating: number;
    phone: string;
    reviewCount: bigint;
    services: Array<Service>;
    photos: Array<string>;
}
export interface Booking {
    id: string;
    statut: StatutBooking;
    clientId: Principal;
    heure: string;
    date: string;
    createdAt: bigint;
    payrexxRef: string;
    montant: number;
    serviceId: string;
    proId: Principal;
}
export interface User {
    id: Principal;
    name: string;
    createdAt: bigint;
    role: Role;
    email: string;
    phone: string;
}
export interface Notification {
    id: string;
    userId: Principal;
    createdAt: bigint;
    read: boolean;
    type: string;
    message: string;
}
export interface Service {
    id: string;
    actif: boolean;
    name: string;
    prix: number;
    description: string;
    duree: bigint;
}
export interface UserProfile {
    name: string;
    role: Role;
    email: string;
    phone: string;
}
export interface Transaction {
    id: string;
    ref: string;
    createdAt: bigint;
    type: TypeTransaction;
    montant: number;
    proId: Principal;
}
export enum Categorie {
    massage = "massage",
    coiffure = "coiffure",
    other = "other",
    onglerie = "onglerie",
    maquillage = "maquillage",
    esthetique = "esthetique"
}
export enum ModeTravail {
    both = "both",
    salon = "salon",
    domicile = "domicile"
}
export enum Role {
    pro = "pro",
    client = "client",
    admin = "admin"
}
export enum StatutBooking {
    cancelled = "cancelled",
    disputed = "disputed",
    pending = "pending",
    completed = "completed",
    confirmed = "confirmed"
}
export enum TypeTransaction {
    subscription = "subscription",
    virement = "virement",
    booking = "booking",
    refund = "refund"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    /**
     * / Add a notification. Admin only (system-generated).
     */
    addNotification(notifId: string, userId: Principal, message: string, type: string): Promise<boolean>;
    /**
     * / Add a service to the caller's pro profile.
     */
    addService(service: Service): Promise<boolean>;
    /**
     * / Add a transaction. Admin only.
     */
    addTransaction(txId: string, proId: Principal, montant: number, type: TypeTransaction, ref: string): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Cancel a booking. Only the client or the pro of that booking may cancel it.
     */
    cancelBooking(bookingId: string): Promise<boolean>;
    /**
     * / Complete a booking. Only the pro of that booking may mark it complete.
     */
    completeBooking(bookingId: string): Promise<boolean>;
    /**
     * / Confirm a booking. Only the pro of that booking may confirm it.
     */
    confirmBooking(bookingId: string): Promise<boolean>;
    /**
     * / Create a booking. Caller must be an authenticated user (client).
     */
    createBooking(bookingId: string, proId: Principal, serviceId: string, date: string, heure: string, montant: number, payrexxRef: string): Promise<boolean>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Get all bookings for a client. Only the client themselves or an admin.
     */
    getClientBookings(clientId: Principal): Promise<Array<Booking>>;
    /**
     * / Get notifications for a user. Only the user themselves or an admin.
     */
    getNotifications(userId: Principal): Promise<Array<Notification>>;
    /**
     * / Get a pro record. Caller can only fetch their own; admins can fetch any.
     */
    getPro(proId: Principal): Promise<Pro | null>;
    /**
     * / Get all bookings for a pro. Only the pro themselves or an admin.
     */
    getProBookings(proId: Principal): Promise<Array<Booking>>;
    /**
     * / Get the sequestered (escrow) amount for a pro.
     * / Sequestre = sum of pending booking amounts not yet released.
     */
    getProSequestre(proId: Principal): Promise<number>;
    /**
     * / Get the available balance (solde) for a pro.
     * / Solde = sum of completed booking amounts minus virements.
     */
    getProSolde(proId: Principal): Promise<number>;
    /**
     * / Get all transactions for a pro. Only the pro themselves or an admin.
     */
    getProTransactions(proId: Principal): Promise<Array<Transaction>>;
    /**
     * / Get a user record. Caller can only fetch their own; admins can fetch any.
     */
    getUser(userId: Principal): Promise<User | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / List all active pros – public endpoint.
     */
    listPros(): Promise<Array<Pro>>;
    /**
     * / List active pros by category – public endpoint.
     */
    listProsByCategory(cat: Categorie): Promise<Array<Pro>>;
    /**
     * / Mark a notification as read. Only the owner of the notification or an admin.
     */
    markNotificationRead(notifId: string): Promise<boolean>;
    /**
     * / Register the caller as a pro.
     */
    registerPro(name: string, categorie: Categorie, bio: string, adresse: string, ville: string, phone: string, email: string, modeTravail: ModeTravail): Promise<boolean>;
    /**
     * / Register the caller as a client user.
     */
    registerUser(phone: string, email: string, name: string): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    /**
     * / Update an existing service on the caller's pro profile.
     */
    updateService(serviceId: string, updated: Service): Promise<boolean>;
}
import type { Booking as _Booking, Categorie as _Categorie, ModeTravail as _ModeTravail, Pro as _Pro, Role as _Role, Service as _Service, StatutBooking as _StatutBooking, Transaction as _Transaction, TypeTransaction as _TypeTransaction, User as _User, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addNotification(arg0: string, arg1: Principal, arg2: string, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addNotification(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNotification(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addService(arg0: Service): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addService(arg0);
            return result;
        }
    }
    async addTransaction(arg0: string, arg1: Principal, arg2: number, arg3: TypeTransaction, arg4: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(arg0, arg1, arg2, to_candid_TypeTransaction_n1(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(arg0, arg1, arg2, to_candid_TypeTransaction_n1(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelBooking(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBooking(arg0);
            return result;
        }
    }
    async completeBooking(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.completeBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeBooking(arg0);
            return result;
        }
    }
    async confirmBooking(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmBooking(arg0);
            return result;
        }
    }
    async createBooking(arg0: string, arg1: Principal, arg2: string, arg3: string, arg4: string, arg5: number, arg6: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClientBookings(arg0: Principal): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClientBookings(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClientBookings(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotifications(arg0: Principal): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications(arg0);
            return result;
        }
    }
    async getPro(arg0: Principal): Promise<Pro | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPro(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPro(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProBookings(arg0: Principal): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProBookings(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProBookings(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProSequestre(arg0: Principal): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getProSequestre(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProSequestre(arg0);
            return result;
        }
    }
    async getProSolde(arg0: Principal): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getProSolde(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProSolde(arg0);
            return result;
        }
    }
    async getProTransactions(arg0: Principal): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProTransactions(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProTransactions(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUser(arg0: Principal): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listPros(): Promise<Array<Pro>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPros();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPros();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProsByCategory(arg0: Categorie): Promise<Array<Pro>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProsByCategory(to_candid_Categorie_n33(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProsByCategory(to_candid_Categorie_n33(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async markNotificationRead(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async registerPro(arg0: string, arg1: Categorie, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: ModeTravail): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.registerPro(arg0, to_candid_Categorie_n33(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, to_candid_ModeTravail_n35(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerPro(arg0, to_candid_Categorie_n33(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, to_candid_ModeTravail_n35(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n37(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n37(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateService(arg0: string, arg1: Service): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateService(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateService(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Booking_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Categorie_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Categorie): Categorie {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_ModeTravail_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ModeTravail): ModeTravail {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Pro_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Pro): Pro {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_StatutBooking_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StatutBooking): StatutBooking {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_TypeTransaction_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TypeTransaction): TypeTransaction {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_User_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Pro]): Pro | null {
    return value.length === 0 ? null : from_candid_Pro_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    statut: _StatutBooking;
    clientId: Principal;
    heure: string;
    date: string;
    createdAt: bigint;
    payrexxRef: string;
    montant: number;
    serviceId: string;
    proId: Principal;
}): {
    id: string;
    statut: StatutBooking;
    clientId: Principal;
    heure: string;
    date: string;
    createdAt: bigint;
    payrexxRef: string;
    montant: number;
    serviceId: string;
    proId: Principal;
} {
    return {
        id: value.id,
        statut: from_candid_StatutBooking_n15(_uploadFile, _downloadFile, value.statut),
        clientId: value.clientId,
        heure: value.heure,
        date: value.date,
        createdAt: value.createdAt,
        payrexxRef: value.payrexxRef,
        montant: value.montant,
        serviceId: value.serviceId,
        proId: value.proId
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    bio: string;
    categorie: _Categorie;
    actif: boolean;
    ville: string;
    subscriptionExpiry: bigint;
    name: string;
    createdAt: bigint;
    email: string;
    modeTravail: _ModeTravail;
    subscriptionActive: boolean;
    adresse: string;
    rating: number;
    phone: string;
    reviewCount: bigint;
    services: Array<_Service>;
    photos: Array<string>;
}): {
    id: Principal;
    bio: string;
    categorie: Categorie;
    actif: boolean;
    ville: string;
    subscriptionExpiry: bigint;
    name: string;
    createdAt: bigint;
    email: string;
    modeTravail: ModeTravail;
    subscriptionActive: boolean;
    adresse: string;
    rating: number;
    phone: string;
    reviewCount: bigint;
    services: Array<Service>;
    photos: Array<string>;
} {
    return {
        id: value.id,
        bio: value.bio,
        categorie: from_candid_Categorie_n20(_uploadFile, _downloadFile, value.categorie),
        actif: value.actif,
        ville: value.ville,
        subscriptionExpiry: value.subscriptionExpiry,
        name: value.name,
        createdAt: value.createdAt,
        email: value.email,
        modeTravail: from_candid_ModeTravail_n22(_uploadFile, _downloadFile, value.modeTravail),
        subscriptionActive: value.subscriptionActive,
        adresse: value.adresse,
        rating: value.rating,
        phone: value.phone,
        reviewCount: value.reviewCount,
        services: value.services,
        photos: value.photos
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    ref: string;
    createdAt: bigint;
    type: _TypeTransaction;
    montant: number;
    proId: Principal;
}): {
    id: string;
    ref: string;
    createdAt: bigint;
    type: TypeTransaction;
    montant: number;
    proId: Principal;
} {
    return {
        id: value.id,
        ref: value.ref,
        createdAt: value.createdAt,
        type: from_candid_TypeTransaction_n27(_uploadFile, _downloadFile, value.type),
        montant: value.montant,
        proId: value.proId
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    name: string;
    createdAt: bigint;
    role: _Role;
    email: string;
    phone: string;
}): {
    id: Principal;
    name: string;
    createdAt: bigint;
    role: Role;
    email: string;
    phone: string;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_Role_n8(_uploadFile, _downloadFile, value.role),
        email: value.email,
        phone: value.phone
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: _Role;
    email: string;
    phone: string;
}): {
    name: string;
    role: Role;
    email: string;
    phone: string;
} {
    return {
        name: value.name,
        role: from_candid_Role_n8(_uploadFile, _downloadFile, value.role),
        email: value.email,
        phone: value.phone
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    disputed: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
}): StatutBooking {
    return "cancelled" in value ? StatutBooking.cancelled : "disputed" in value ? StatutBooking.disputed : "pending" in value ? StatutBooking.pending : "completed" in value ? StatutBooking.completed : "confirmed" in value ? StatutBooking.confirmed : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    massage: null;
} | {
    coiffure: null;
} | {
    other: null;
} | {
    onglerie: null;
} | {
    maquillage: null;
} | {
    esthetique: null;
}): Categorie {
    return "massage" in value ? Categorie.massage : "coiffure" in value ? Categorie.coiffure : "other" in value ? Categorie.other : "onglerie" in value ? Categorie.onglerie : "maquillage" in value ? Categorie.maquillage : "esthetique" in value ? Categorie.esthetique : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    both: null;
} | {
    salon: null;
} | {
    domicile: null;
}): ModeTravail {
    return "both" in value ? ModeTravail.both : "salon" in value ? ModeTravail.salon : "domicile" in value ? ModeTravail.domicile : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subscription: null;
} | {
    virement: null;
} | {
    booking: null;
} | {
    refund: null;
}): TypeTransaction {
    return "subscription" in value ? TypeTransaction.subscription : "virement" in value ? TypeTransaction.virement : "booking" in value ? TypeTransaction.booking : "refund" in value ? TypeTransaction.refund : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pro: null;
} | {
    client: null;
} | {
    admin: null;
}): Role {
    return "pro" in value ? Role.pro : "client" in value ? Role.client : "admin" in value ? Role.admin : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Pro>): Array<Pro> {
    return value.map((x)=>from_candid_Pro_n18(_uploadFile, _downloadFile, x));
}
function to_candid_Categorie_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Categorie): _Categorie {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_ModeTravail_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ModeTravail): _ModeTravail {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function to_candid_TypeTransaction_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TypeTransaction): _TypeTransaction {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n38(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: Role;
    email: string;
    phone: string;
}): {
    name: string;
    role: _Role;
    email: string;
    phone: string;
} {
    return {
        name: value.name,
        role: to_candid_Role_n39(_uploadFile, _downloadFile, value.role),
        email: value.email,
        phone: value.phone
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TypeTransaction): {
    subscription: null;
} | {
    virement: null;
} | {
    booking: null;
} | {
    refund: null;
} {
    return value == TypeTransaction.subscription ? {
        subscription: null
    } : value == TypeTransaction.virement ? {
        virement: null
    } : value == TypeTransaction.booking ? {
        booking: null
    } : value == TypeTransaction.refund ? {
        refund: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Categorie): {
    massage: null;
} | {
    coiffure: null;
} | {
    other: null;
} | {
    onglerie: null;
} | {
    maquillage: null;
} | {
    esthetique: null;
} {
    return value == Categorie.massage ? {
        massage: null
    } : value == Categorie.coiffure ? {
        coiffure: null
    } : value == Categorie.other ? {
        other: null
    } : value == Categorie.onglerie ? {
        onglerie: null
    } : value == Categorie.maquillage ? {
        maquillage: null
    } : value == Categorie.esthetique ? {
        esthetique: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ModeTravail): {
    both: null;
} | {
    salon: null;
} | {
    domicile: null;
} {
    return value == ModeTravail.both ? {
        both: null
    } : value == ModeTravail.salon ? {
        salon: null
    } : value == ModeTravail.domicile ? {
        domicile: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    pro: null;
} | {
    client: null;
} | {
    admin: null;
} {
    return value == Role.pro ? {
        pro: null
    } : value == Role.client ? {
        client: null
    } : value == Role.admin ? {
        admin: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
