/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : string,
  'statut' : StatutBooking,
  'clientId' : Principal,
  'heure' : string,
  'date' : string,
  'createdAt' : bigint,
  'payrexxRef' : string,
  'montant' : number,
  'serviceId' : string,
  'proId' : Principal,
}
export type Categorie = { 'massage' : null } |
  { 'coiffure' : null } |
  { 'other' : null } |
  { 'onglerie' : null } |
  { 'maquillage' : null } |
  { 'esthetique' : null };
export type ModeTravail = { 'both' : null } |
  { 'salon' : null } |
  { 'domicile' : null };
export interface Notification {
  'id' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'read' : boolean,
  'type' : string,
  'message' : string,
}
export interface Pro {
  'id' : Principal,
  'bio' : string,
  'categorie' : Categorie,
  'actif' : boolean,
  'ville' : string,
  'subscriptionExpiry' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'modeTravail' : ModeTravail,
  'subscriptionActive' : boolean,
  'adresse' : string,
  'rating' : number,
  'phone' : string,
  'reviewCount' : bigint,
  'services' : Array<Service>,
  'photos' : Array<string>,
}
export type Role = { 'pro' : null } |
  { 'client' : null } |
  { 'admin' : null };
export interface Service {
  'id' : string,
  'actif' : boolean,
  'name' : string,
  'prix' : number,
  'description' : string,
  'duree' : bigint,
}
export type StatutBooking = { 'cancelled' : null } |
  { 'disputed' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export interface Transaction {
  'id' : string,
  'ref' : string,
  'createdAt' : bigint,
  'type' : TypeTransaction,
  'montant' : number,
  'proId' : Principal,
}
export type TypeTransaction = { 'subscription' : null } |
  { 'virement' : null } |
  { 'booking' : null } |
  { 'refund' : null };
export interface User {
  'id' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'role' : Role,
  'email' : string,
  'phone' : string,
}
export interface UserProfile {
  'name' : string,
  'role' : Role,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Add a notification. Admin only (system-generated).
   */
  'addNotification' : ActorMethod<[string, Principal, string, string], boolean>,
  /**
   * / Add a service to the caller's pro profile.
   */
  'addService' : ActorMethod<[Service], boolean>,
  /**
   * / Add a transaction. Admin only.
   */
  'addTransaction' : ActorMethod<
    [string, Principal, number, TypeTransaction, string],
    boolean
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Cancel a booking. Only the client or the pro of that booking may cancel it.
   */
  'cancelBooking' : ActorMethod<[string], boolean>,
  /**
   * / Complete a booking. Only the pro of that booking may mark it complete.
   */
  'completeBooking' : ActorMethod<[string], boolean>,
  /**
   * / Confirm a booking. Only the pro of that booking may confirm it.
   */
  'confirmBooking' : ActorMethod<[string], boolean>,
  /**
   * / Create a booking. Caller must be an authenticated user (client).
   */
  'createBooking' : ActorMethod<
    [string, Principal, string, string, string, number, string],
    boolean
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Get all bookings for a client. Only the client themselves or an admin.
   */
  'getClientBookings' : ActorMethod<[Principal], Array<Booking>>,
  /**
   * / Get notifications for a user. Only the user themselves or an admin.
   */
  'getNotifications' : ActorMethod<[Principal], Array<Notification>>,
  /**
   * / Get a pro record. Caller can only fetch their own; admins can fetch any.
   */
  'getPro' : ActorMethod<[Principal], [] | [Pro]>,
  /**
   * / Get all bookings for a pro. Only the pro themselves or an admin.
   */
  'getProBookings' : ActorMethod<[Principal], Array<Booking>>,
  /**
   * / Get the sequestered (escrow) amount for a pro.
   * / Sequestre = sum of pending booking amounts not yet released.
   */
  'getProSequestre' : ActorMethod<[Principal], number>,
  /**
   * / Get the available balance (solde) for a pro.
   * / Solde = sum of completed booking amounts minus virements.
   */
  'getProSolde' : ActorMethod<[Principal], number>,
  /**
   * / Get all transactions for a pro. Only the pro themselves or an admin.
   */
  'getProTransactions' : ActorMethod<[Principal], Array<Transaction>>,
  /**
   * / Get a user record. Caller can only fetch their own; admins can fetch any.
   */
  'getUser' : ActorMethod<[Principal], [] | [User]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / List all active pros – public endpoint.
   */
  'listPros' : ActorMethod<[], Array<Pro>>,
  /**
   * / List active pros by category – public endpoint.
   */
  'listProsByCategory' : ActorMethod<[Categorie], Array<Pro>>,
  /**
   * / Mark a notification as read. Only the owner of the notification or an admin.
   */
  'markNotificationRead' : ActorMethod<[string], boolean>,
  /**
   * / Register the caller as a pro.
   */
  'registerPro' : ActorMethod<
    [string, Categorie, string, string, string, string, string, ModeTravail],
    boolean
  >,
  /**
   * / Register the caller as a client user.
   */
  'registerUser' : ActorMethod<[string, string, string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Update an existing service on the caller's pro profile.
   */
  'updateService' : ActorMethod<[string, Service], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];