/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Service = IDL.Record({
  'id' : IDL.Text,
  'actif' : IDL.Bool,
  'name' : IDL.Text,
  'prix' : IDL.Float64,
  'description' : IDL.Text,
  'duree' : IDL.Nat,
});
export const TypeTransaction = IDL.Variant({
  'subscription' : IDL.Null,
  'virement' : IDL.Null,
  'booking' : IDL.Null,
  'refund' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Role = IDL.Variant({
  'pro' : IDL.Null,
  'client' : IDL.Null,
  'admin' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : Role,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const StatutBooking = IDL.Variant({
  'cancelled' : IDL.Null,
  'disputed' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Text,
  'statut' : StatutBooking,
  'clientId' : IDL.Principal,
  'heure' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'payrexxRef' : IDL.Text,
  'montant' : IDL.Float64,
  'serviceId' : IDL.Text,
  'proId' : IDL.Principal,
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'read' : IDL.Bool,
  'type' : IDL.Text,
  'message' : IDL.Text,
});
export const Categorie = IDL.Variant({
  'massage' : IDL.Null,
  'coiffure' : IDL.Null,
  'other' : IDL.Null,
  'onglerie' : IDL.Null,
  'maquillage' : IDL.Null,
  'esthetique' : IDL.Null,
});
export const ModeTravail = IDL.Variant({
  'both' : IDL.Null,
  'salon' : IDL.Null,
  'domicile' : IDL.Null,
});
export const Pro = IDL.Record({
  'id' : IDL.Principal,
  'bio' : IDL.Text,
  'categorie' : Categorie,
  'actif' : IDL.Bool,
  'ville' : IDL.Text,
  'subscriptionExpiry' : IDL.Int,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'modeTravail' : ModeTravail,
  'subscriptionActive' : IDL.Bool,
  'adresse' : IDL.Text,
  'rating' : IDL.Float64,
  'phone' : IDL.Text,
  'reviewCount' : IDL.Nat,
  'services' : IDL.Vec(Service),
  'photos' : IDL.Vec(IDL.Text),
});
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'ref' : IDL.Text,
  'createdAt' : IDL.Int,
  'type' : TypeTransaction,
  'montant' : IDL.Float64,
  'proId' : IDL.Principal,
});
export const User = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : Role,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addNotification' : IDL.Func(
      [IDL.Text, IDL.Principal, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'addService' : IDL.Func([Service], [IDL.Bool], []),
  'addTransaction' : IDL.Func(
      [IDL.Text, IDL.Principal, IDL.Float64, TypeTransaction, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelBooking' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'completeBooking' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'confirmBooking' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'createBooking' : IDL.Func(
      [
        IDL.Text,
        IDL.Principal,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
      ],
      [IDL.Bool],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClientBookings' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getNotifications' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'getPro' : IDL.Func([IDL.Principal], [IDL.Opt(Pro)], ['query']),
  'getProBookings' : IDL.Func([IDL.Principal], [IDL.Vec(Booking)], ['query']),
  'getProSequestre' : IDL.Func([IDL.Principal], [IDL.Float64], ['query']),
  'getProSolde' : IDL.Func([IDL.Principal], [IDL.Float64], ['query']),
  'getProTransactions' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getUser' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listPros' : IDL.Func([], [IDL.Vec(Pro)], ['query']),
  'listProsByCategory' : IDL.Func([Categorie], [IDL.Vec(Pro)], ['query']),
  'markNotificationRead' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'registerPro' : IDL.Func(
      [
        IDL.Text,
        Categorie,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ModeTravail,
      ],
      [IDL.Bool],
      [],
    ),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateService' : IDL.Func([IDL.Text, Service], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Service = IDL.Record({
    'id' : IDL.Text,
    'actif' : IDL.Bool,
    'name' : IDL.Text,
    'prix' : IDL.Float64,
    'description' : IDL.Text,
    'duree' : IDL.Nat,
  });
  const TypeTransaction = IDL.Variant({
    'subscription' : IDL.Null,
    'virement' : IDL.Null,
    'booking' : IDL.Null,
    'refund' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Role = IDL.Variant({
    'pro' : IDL.Null,
    'client' : IDL.Null,
    'admin' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : Role,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const StatutBooking = IDL.Variant({
    'cancelled' : IDL.Null,
    'disputed' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Text,
    'statut' : StatutBooking,
    'clientId' : IDL.Principal,
    'heure' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'payrexxRef' : IDL.Text,
    'montant' : IDL.Float64,
    'serviceId' : IDL.Text,
    'proId' : IDL.Principal,
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'read' : IDL.Bool,
    'type' : IDL.Text,
    'message' : IDL.Text,
  });
  const Categorie = IDL.Variant({
    'massage' : IDL.Null,
    'coiffure' : IDL.Null,
    'other' : IDL.Null,
    'onglerie' : IDL.Null,
    'maquillage' : IDL.Null,
    'esthetique' : IDL.Null,
  });
  const ModeTravail = IDL.Variant({
    'both' : IDL.Null,
    'salon' : IDL.Null,
    'domicile' : IDL.Null,
  });
  const Pro = IDL.Record({
    'id' : IDL.Principal,
    'bio' : IDL.Text,
    'categorie' : Categorie,
    'actif' : IDL.Bool,
    'ville' : IDL.Text,
    'subscriptionExpiry' : IDL.Int,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'modeTravail' : ModeTravail,
    'subscriptionActive' : IDL.Bool,
    'adresse' : IDL.Text,
    'rating' : IDL.Float64,
    'phone' : IDL.Text,
    'reviewCount' : IDL.Nat,
    'services' : IDL.Vec(Service),
    'photos' : IDL.Vec(IDL.Text),
  });
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'ref' : IDL.Text,
    'createdAt' : IDL.Int,
    'type' : TypeTransaction,
    'montant' : IDL.Float64,
    'proId' : IDL.Principal,
  });
  const User = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : Role,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addNotification' : IDL.Func(
        [IDL.Text, IDL.Principal, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'addService' : IDL.Func([Service], [IDL.Bool], []),
    'addTransaction' : IDL.Func(
        [IDL.Text, IDL.Principal, IDL.Float64, TypeTransaction, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelBooking' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'completeBooking' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'confirmBooking' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'createBooking' : IDL.Func(
        [
          IDL.Text,
          IDL.Principal,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
        ],
        [IDL.Bool],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClientBookings' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getNotifications' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getPro' : IDL.Func([IDL.Principal], [IDL.Opt(Pro)], ['query']),
    'getProBookings' : IDL.Func([IDL.Principal], [IDL.Vec(Booking)], ['query']),
    'getProSequestre' : IDL.Func([IDL.Principal], [IDL.Float64], ['query']),
    'getProSolde' : IDL.Func([IDL.Principal], [IDL.Float64], ['query']),
    'getProTransactions' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUser' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listPros' : IDL.Func([], [IDL.Vec(Pro)], ['query']),
    'listProsByCategory' : IDL.Func([Categorie], [IDL.Vec(Pro)], ['query']),
    'markNotificationRead' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'registerPro' : IDL.Func(
        [
          IDL.Text,
          Categorie,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ModeTravail,
        ],
        [IDL.Bool],
        [],
      ),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateService' : IDL.Func([IDL.Text, Service], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };